### ISSUE TITLE
Code Generator should not overwrite kernels with same content

### ISSUE THREAD

**Issue by martin-ueding** [JeffersonLab/qphix-codegen#10]
The build system only looks at the time stamps, not at the contents. The code generators are always executed, which means that the time stamps on the kernels are always updated. Even if the kernels have not changed, they have to be re-compiled.

This is currently wasting my time, so I want to add something that will load in the kernel to be written if it exists, checks for inequality and then writes it out.

**Comment by bjoo** [comment]
Yes. This is a nuisance when developing new kernels. I think one issue is that comes from the independent subbuild. 
If you could fix, that would be a big help. Perhaps this could be handled in the Python rather than the build system?

Best, 
 B
> On Jun 21, 2017, at 11:21 AM, Martin Ueding <notifications@github.com> wrote:
> 
> The build system only looks at the time stamps, not at the contents. The code generators are always executed, which means that the time stamps on the kernels are always updated. Even if the kernels have not changed, they have to be re-compiled.
> 
> This is currently wasting my time, so I want to add something that will load in the kernel to be written if it exists, checks for inequality and then writes it out.
> 
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub, or mute the thread.
> 

--------------------------------------------------------------------------------------
Dr Balint Joo              High Performance Computational Scientist
Jefferson Lab
12000 Jefferson Ave, Suite 3, MS 12B2, Room F217,
Newport News, VA 23606, USA
Tel: +1-757-269-5339,      Fax: +1-757-269-5427
email: bjoo@jlab.org       
-------------------------------------------------------------------------------------

**Comment by martin-ueding** [comment]
That's fixed now in the CMake branch. I just changed the `dumpIVector` function to compare to the previous version. If the file does not exist, the previous content is taken as empty.
